import { Dialog, DialogContent, DialogTitle, Button } from "@bluethub/ui-kit";
import { ClipboardCopy, KeyRound } from "lucide-react";
import toast from "react-hot-toast";
import type { ResetStudentPasswordData } from "@/services/admin";

interface ResetPasswordDialogProps {
  data: ResetStudentPasswordData | null;
  onClose: () => void;
}

// Shows the one-time temp password generated by POST
// /api/User/students/{studentId}/reset-password so a staff member can read
// and share it with the student — it only ever appears here, so unlike a
// toast this needs to stay on screen until they've copied it.
const ResetPasswordDialog = ({ data, onClose }: ResetPasswordDialogProps) => {
  const handleCopy = async () => {
    if (!data?.tempPassword) return;
    try {
      await navigator.clipboard.writeText(data.tempPassword);
      toast.success("Temporary password copied to clipboard");
    } catch {
      toast.error("Could not copy password");
    }
  };

  return (
    <Dialog open={!!data} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-sm rounded-2xl p-0 overflow-hidden">
        <div className="px-5 py-4 border-b border-gray-100 flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-emerald-100 flex items-center justify-center shrink-0">
            <KeyRound className="w-4 h-4 text-emerald-600" />
          </div>
          <div>
            <DialogTitle className="text-sm font-bold text-gray-900">Temporary Password Generated</DialogTitle>
            <p className="text-[11px] text-gray-400 mt-0.5">For {data?.studentName ?? "the student"}</p>
          </div>
        </div>

        <div className="p-5 space-y-3">
          <p className="text-xs text-gray-500 leading-relaxed">
            Share this password with the student directly. It only works to set a new password —
            it isn't an ongoing login.
          </p>
          <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3">
            <span className="flex-1 font-mono text-base font-bold tracking-wide text-emerald-700 select-all">
              {data?.tempPassword}
            </span>
            <button
              onClick={handleCopy}
              title="Copy password"
              className="text-emerald-500 hover:text-emerald-700 transition-colors shrink-0"
            >
              <ClipboardCopy className="w-4 h-4" />
            </button>
          </div>
        </div>

        <div className="px-5 pb-5 pt-1 flex justify-end">
          <Button
            onClick={onClose}
            className="h-10 rounded-lg bg-chestnut hover:bg-chestnut/90 text-white px-5 text-sm font-semibold"
          >
            Done
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ResetPasswordDialog;
